PI/PI/urls.py
from django.contrib import admin
from django.urls import path, include
from ong.urls import urlpatternscad as url_ong_cad, urlpatterns as url_ong
from empresa.urls import urlpatternscad as url_empresa_cad
from home.urls import urlpatterns as url_home
from pessoa.urls import urlpatternscad as url_pessoa_cad
from home.urls import urlpatterns as url_home
from login.urls import urlpatterns as url_login_logout
from pessoa.urls import urlpatternsdoacao as url_pessoa_doacao
from empresa.urls import urlpatternsdoacao as url_empresa_doacao

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cadastro/empresa/', include(url_empresa_cad)),
    path('cadastro/pessoa/', include(url_pessoa_cad)),
    path('cadastro/ong/', include(url_ong_cad)),
    path('home/', include(url_home)),
    path('auth/', include(url_login_logout)),
    path('doacao/pessoa/', include(url_pessoa_doacao)),
    path('doacao/', include(url_empresa_doacao)),
    path('', include(url_home)),
    path('distribuicao/', include(url_ong)),
    path('pessoa/pagamento/', include(url_pessoa_doacao))
]

PI/ong/urls.py
from django.urls import path
from ong.views import OngCadastro, OngDistribuicao, OngDoacaoMinha

urlpatternscad = [
    path('', OngCadastro.as_view(), name='ongpostcad'),
    path('<int:etapa>/', OngCadastro.as_view(), name='onggetcad')
]

urlpatterns = [
    path('<int:numero_pagina>/', OngDistribuicao.as_view(), name='distribuicao_ong'),
    path('recebida/<int:numero_pagina>/', OngDoacaoMinha.as_view(), name='doacao_recebida'),
]

PI/ong/models.py
from djongo import models
from utils.models.model_padrao import ModeloPadrao

# Create your models here.

class Ong(ModeloPadrao):
    objetivo_ong = models.CharField(max_length=256)
    
    def __str__(self):
        return self.nome
    
class DoacaoRecebida(models.Model):
    id = models.ObjectIdField(primary_key=True)
    id_empresa = models.CharField(max_length=256)
    id_ong = models.CharField(max_length=256)
    nome_produto = models.CharField(max_length=100)
    descricao_produto = models.CharField(max_length=256, blank=True, null=True)
    quantidade_produto = models.CharField(max_length=20)
    unidade_medida_produto = models.CharField(max_length=50)
    categoria_produto = models.CharField(max_length=50)
    data_doado_produto = models.DateTimeField()
    data_recebido_produto = models.DateTimeField(auto_now_add=True)

PI/utils/models/model_padrao.py
from djongo import models
from django.contrib.auth.hashers import make_password, check_password

class ModeloPadrao(models.Model):
    id = models.ObjectIdField(primary_key=True)
    nome = models.CharField(max_length=100)
    cnpj = models.CharField(max_length=20)
    email_login = models.EmailField(max_length=100)
    senha_login = models.CharField(max_length=100)
    cep = models.CharField(max_length=20)
    estado = models.CharField(max_length=100)
    cidade = models.CharField(max_length=100)
    bairro = models.CharField(max_length=100)
    rua = models.CharField(max_length=100)
    numero = models.CharField(max_length=10)
    complemento = models.CharField(max_length=100, null=True, blank=True)
    nome_representante = models.CharField(max_length=100)
    cpf_representante = models.CharField(max_length=11)
    telefone_representante = models.CharField(max_length=20)
    email_representante = models.EmailField(max_length=100)

    def set_senha(self, senha_login):
        self.senha_login = make_password(senha_login)

    def verifica_senha(self, senha_login):
        return check_password(senha_login, self.senha_login)

    class Meta:
        abstract = True

PI/ong/forms.py
from django import forms
from ong.models import Ong
from services.validacao import Validacao
from django_select2.forms import Select2Widget

class OngFormUm(forms.ModelForm):
    class Meta:
        model = Ong
        fields = [
            'nome',
            'cnpj',
            'objetivo_ong',
            'email_login',
            'senha_login',
        ]
        widgets = {
            'nome': forms.TextInput(attrs={
                'class': 'form-control',
            }),
            'cnpj': forms.TextInput(attrs={
                'class': 'form-control',
            }),
            'objetivo_ong': forms.TextInput(attrs={
                'class': 'form-control',
            }),
            'email_login': forms.TextInput(attrs={
                'class': 'form-control',
            }),
            'senha_login': forms.PasswordInput(attrs={
                'class': 'form-control',
                'type': 'password',
            }),
        }
    
    def clean_cnpj(self):
        cnpj = self.cleaned_data.get('cnpj')
        cnpj = Validacao.verifica_cnpj(cnpj)
        if not cnpj:
            raise forms.ValidationError('CNPJ inválido')
        if cnpj == 'cadastrado':
            raise forms.ValidationError('CNPJ já cadastrado')
        return cnpj
    

    def clean_email_login(self):
        email_login = self.cleaned_data.get('email_login')
        email_login = Validacao.verifica_email(email_login)
        if email_login == 'cadastrado':
            raise forms.ValidationError('Email já cadastrado')
        return email_login
    
    def clean_senha_login(self):
        senha_login = self.cleaned_data.get('senha_login')
        senha_login = Validacao.verifica_senha(senha_login)
        if not senha_login:
            raise forms.ValidationError('Senha inválida')
        return senha_login

class OngFormDois(forms.ModelForm):
    class Meta:
        model = Ong
        fields = [
            'cep',
            'estado',
            'cidade',
            'bairro',
            'rua',
            'numero',
            'complemento',
        ]
        widgets = {
            'cep': forms.TextInput(attrs={
                'class': 'form-control',
            }),
            'estado': forms.TextInput(attrs={
                'class': 'form-control',
            }),
            'cidade': forms.TextInput(attrs={
                'class': 'form-control',
            }),
            'bairro': forms.TextInput(attrs={
                'class': 'form-control',
            }),
            'rua': forms.TextInput(attrs={
                'class': 'form-control',
            }),
            'numero': forms.TextInput(attrs={
                'class': 'form-control',
            }),
            'complemento': forms.TextInput(attrs={
                'class': 'form-control',
            }),
        }

    def clean_cep(self):
        cep = self.cleaned_data.get('cep')
        cep = Validacao.verifica_cep(cep)
        if not cep:
            raise forms.ValidationError('CEP inválido')
        return cep

class OngFormTres(forms.ModelForm):
    class Meta:
        model = Ong
        fields = [
            'nome_representante',
            'cpf_representante',
            'telefone_representante',
            'email_representante',
        ]
        widgets = {
            'nome_representante': forms.TextInput(attrs={
                'class': 'form-control',
            }),
            'cpf_representante': forms.TextInput(attrs={
                'class': 'form-control',
            }),
            'telefone_representante': forms.TextInput(attrs={
                'class': 'form-control',
            }),
            'email_representante': forms.TextInput(attrs={
                'class': 'form-control',
            })
        }

    def clean_nome_representante(self):
        nome_representante = self.cleaned_data.get('nome_representante')
        nome_representante = Validacao.verifica_nome_representante(nome_representante)
        if not nome_representante:
            raise forms.ValidationError('Nome do representante inválido')
        return nome_representante
    
    def clean_cpf_representante(self):
        cpf_representante = self.cleaned_data.get('cpf_representante')
        cpf_representante = Validacao.verifica_cpf(cpf_representante)
        if not cpf_representante:
            raise forms.ValidationError('CPF do representante inválido')
        return cpf_representante
    
    def clean_telefone_representante(self):
        telefone_representante = self.cleaned_data.get('telefone_representante')
        telefone_representante = Validacao.verifica_telefone(telefone_representante)
        if not telefone_representante:
            raise forms.ValidationError('Telefone do representante inválido')
        return telefone_representante

class OngCompleta(forms.ModelForm):
    class Meta:
        model = Ong
        fields = [
            'nome',
            'cnpj',
            'objetivo_ong',
            'email_login',
            'senha_login',
            'cep', 
            'estado',
            'cidade',
            'bairro',
            'rua',
            'numero',
            'complemento',
            'nome_representante',
            'cpf_representante',
            'telefone_representante',
            'email_representante',
        ]

PI/ong/views.py
from django.http.response import HttpResponse as HttpResponse
from django.shortcuts import render, redirect
from ong.forms import OngFormUm, OngFormDois, OngFormTres, OngCompleta
from django.views import View
from empresa.models import Empresa, Doacao
from ong.models import Ong, DoacaoRecebida
from django.core.paginator import Paginator
from services.contexto import GeraContexto

class OngCadastro(View):
    def __init__(self, *args, **kwargs):
        self.templates = {
            1: ['cadastro_um_ong.html', OngFormUm],
            2: ['cadastro_dois_ong.html', OngFormDois],
            3: ['cadastro_tres_ong.html', OngFormTres]
        }
        super().__init__(*args, **kwargs)
    def get(self, request, etapa):
        template = self.templates[etapa][0]
        form = self.templates[etapa][1]()
        if etapa > 1 and not f'etapa{etapa-1}' in request.session:
            return redirect('onggetcad', etapa=1)
        return render(request=request, template_name=template, context={'form': form}) 
    def post(self, request):
        chave = 1 if request.POST.get('etapa1', '') else (2 if request.POST.get('etapa2', '') else (3 if request.POST.get('etapa3', '') else ''))
        if chave == '':
            return redirect('home')
        form = self.templates[chave][1](request.POST)
        if form.is_valid():
            if chave == 1:
                request.session['ong'] = form.cleaned_data
                request.session['etapa1'] = True
            elif chave == 2:
                request.session['ong'] = request.session['ong'] | form.cleaned_data
                request.session['etapa2'] = True
            elif chave == 3:
                form_completo = OngCompleta(request.session['ong'] | form.cleaned_data)
                ong = form_completo.save(commit=False)
                ong.set_senha(form_completo.cleaned_data['senha_login'])
                ong.save()
                return redirect('login')
            request.session.modified = True
            return redirect('onggetcad', etapa = chave + 1)
        else:
            return render(request=request, template_name=self.templates[chave][0], context={'form': form}, status=400)
    
class OngDistribuicao(View):
    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_superuser:
            return redirect('home')
        return super().dispatch(request, *args, **kwargs)
    def get(self, request, numero_pagina):
        empresas = {empresa.id: empresa.nome for empresa in Empresa.objects.all()}
        ongs = Ong.objects.all().values('id', 'nome')
        nomes = {i['id']: i['nome'] for i in ongs}
        doacoes = Doacao.objects.filter(disponivel_produto__in=[True]).values('id_empresa', 'id', 'nome_produto', 'quantidade_produto', 'unidade_medida_produto', 'data_doado_produto', 'disponivel_produto') 
        lista_contexto = GeraContexto.ContextoEmpresa(doacoes, empresas)
        doacao_paginada = Paginator(lista_contexto, 10)
        pagina = doacao_paginada.get_page(numero_pagina)
        return render(request=request, template_name='distribui_doacao_ong.html', context={'doacoes': pagina, 'ongs': nomes})
    def post(self, request, numero_pagina):
        dicionario = {int(i): int(j) for i, e in request.POST.items() for j in e if i.isdigit()} # Primeiro o id da doaçao, segundo o da ong que vai receber
        for i, e in dicionario.items():
            doacao = Doacao.objects.get(id=i)
            doacao.disponivel_produto = False
            doacao.save()
            ong = Ong.objects.get(id=e)
            doacao_recebida = DoacaoRecebida(
                id_empresa = doacao.id_empresa,
                id_ong = ong.id,
                nome_produto = doacao.nome_produto,
                descricao_produto = doacao.descricao_produto,
                quantidade_produto = doacao.quantidade_produto,
                unidade_medida_produto = doacao.unidade_medida_produto,
                categoria_produto = doacao.categoria_produto,
                data_doado_produto = doacao.data_doado_produto
            )
            doacao_recebida.save()
        return redirect('distribuicao_ong', numero_pagina=numero_pagina)
    
class OngDoacaoMinha(View):
    def dispatch(self, request, *args, **kwargs):
        if 'id_ong' not in request.session:
            return redirect('login')
        return super().dispatch(request, *args, **kwargs)
    def get(self, request, numero_pagina):
        empresas = {empresa.id: empresa.nome for empresa in Empresa.objects.all()}
        doacoes = DoacaoRecebida.objects.values('id', 'id_empresa', 'nome_produto', 'quantidade_produto', 'unidade_medida_produto', 'data_doado_produto').filter(id_ong=request.session['id_ong'])
        lista_contexto = GeraContexto.ContextoEmpresa(doacoes, empresas, ong=True)
        doacao_paginada = Paginator(lista_contexto, 10)
        pagina = doacao_paginada.get_page(numero_pagina)
        return render(request=request, template_name='doacao_recebida.html', context={'doacoes': pagina, 'logout': 'ong'})

PI/ong/templates/cadastro_dois_ong.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <title>Cadastro de Endereço da ONG</title>
    <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
    <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" />
    <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
</head>
<body id="page-top">

    <script src="{% static 'script/Password.js' %}"></script>

    {% if logout %}
        {% include 'Menu/menuCLoginBasic.html' %}
    {% else %}
        {% include 'Menu/menuSLoginBasic.html' %}
    {% endif %}  

    <section class="page-section d-flex justify-content-center align-items-center" id="cadastro-endereco">
        <div class="container">
            <div class="text-center mb-4">
                <h2 class="section-heading text-uppercase">Cadastro de Endereço da ONG</h2>
                <h3 class="section-subheading">Informe os dados de endereço da sua ONG</h3>
            </div>
            
            <form action="{% url 'ongpostcad' %}" method="post">
                {% csrf_token %}
                
                <div class="row justify-content-center2 mb-3">
                    <div class="col-md-3">
                        <label for="id_cep">CEP:</label>
                        <label id="cep_invalido" style="visibility: hidden;" class="text-danger ms-2">CEP inválido</label>
                        {{ form.cep }}
                        {% if form.cep.errors %}
                            {% for error in form.cep.errors %}
                                <label>{{ error }}</label>
                            {% endfor %}
                        {% endif %}
                    </div>

                    <div class="col-md-3">
                        <label for="id_estado">Estado:</label>
                        {{ form.estado }}
                    </div>
                </div>

                <div class="row justify-content-center2 mb-3">
                    <div class="col-md-3">
                        <label for="id_cidade">Cidade:</label>
                        {{ form.cidade }}
                    </div>

                    <div class="col-md-3">
                        <label for="id_bairro">Bairro:</label>
                        {{ form.bairro }}
                    </div>
                </div>

                <div class="row justify-content-center2 mb-3">
                    <div class="col-md-3">
                        <label for="id_rua">Rua:</label>
                        {{ form.rua }}
                    </div>

                    <div class="col-md-3">
                        <label for="id_numero">Número:</label>
                        {{ form.numero }}
                    </div>
                </div>

                <div class="row justify-content-center mb-3">
                    <div class="col-md-6">
                        <label for="id_complemento">Complemento:</label>
                        {{ form.complemento }}
                    </div>
                </div>

                <input type="hidden" name="etapa2" value="2">

                <div class="text-center mt-4">
                    <input type="submit" class="btn btn-primary btn-xl text-uppercase text-black" value="Próximo">
                </div>
            </form>
        </div>
    </section>

    <script>
        const cep = document.getElementById('id_cep')
        const estado = document.getElementById('id_estado')
        const cidade = document.getElementById('id_cidade')
        const bairro = document.getElementById('id_bairro')
        const rua = document.getElementById('id_rua')

        cep.addEventListener('blur', () => {
            const cep_value = cep.value.replace(/\D/g, '');
            new Cep(cep_value);
        })
    </script>
    <script src="{% static 'script/cep.js' %}"></script>

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js" crossorigin="anonymous"></script>
    <script src="https://apis.google.com/js/platform.js" async defer></script>
    <script src="{% static 'js/scripts.js' %}"></script>
</body>
</html>

PI/ong/templates/cadastro_tres_ong.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <title>Cadastro de ONG - Representante Legal</title>
    <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
    <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" />
    <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
</head>
<body id="page-top">

    <script src="{% static 'script/Password.js' %}"></script>

    {% if logout %}
        {% include 'Menu/menuCLoginBasic.html' %}
    {% else %}
        {% include 'Menu/menuSLoginBasic.html' %}
    {% endif %}   

    <section class="page-section d-flex justify-content-center align-items-center" id="cadastro">
        <div class="container">
            <div class="text-center mb-4">
                <h2 class="section-heading text-uppercase">Representante Legal</h2>
                <h3 class="section-subheading">Informe os dados do representante legal</h3>
            </div>

            <form action="{% url 'ongpostcad' %}" method="post">
                {% csrf_token %}

                <div class="row justify-content-center mb-3">
                    <div class="col-md-4">
                        <div class="d-flex justify-content-between">
                            <label for="id_nome_representante">Nome do representante:</label>
                            <div class="text-danger ms-2">
                                {% if form.nome_representante.errors %}
                                    {% for error in form.nome_representante.errors %}
                                        <label>{{ error }}</label>
                                    {% endfor %}
                                {% endif %}
                            </div>
                        </div>
                        {{ form.nome_representante }}
                    </div>
                </div>

                <div class="row justify-content-center mb-3">
                    <div class="col-md-4">
                        <div class="d-flex justify-content-between">
                            <label for="id_cpf_representante">CPF:</label>
                            <div class="text-danger ms-2">
                                {% if form.cpf_representante.errors %}
                                    {% for error in form.cpf_representante.errors %}
                                        <label>{{ error }}</label>
                                    {% endfor %}
                                {% endif %}
                            </div>
                        </div>
                        {{ form.cpf_representante }}
                    </div>
                </div>

                <div class="row justify-content-center mb-3">
                    <div class="col-md-4">
                        <div class="d-flex justify-content-between">
                            <label for="id_telefone_representante">Telefone:</label>
                            <div class="text-danger ms-2">
                                {% if form.telefone_representante.errors %}
                                    {% for error in form.telefone_representante.errors %}
                                        <label>{{ error }}</label>
                                    {% endfor %}
                                {% endif %}
                            </div>
                        </div>
                        {{ form.telefone_representante }}
                    </div>
                </div>

                <div class="row justify-content-center mb-3">
                    <div class="col-md-4">
                        <label for="id_email_representante">E-mail:</label>
                        {{ form.email_representante }}
                    </div>
                </div>

                <input type="hidden" name="etapa3" value="3">

                <div class="text-center mt-4">
                    <input type="submit" class="btn btn-primary btn-xl text-uppercase text-black" value="Concluir">
                </div>
            </form>
        </div>
    </section>

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js" crossorigin="anonymous"></script>
    <script src="{% static 'js/scripts.js' %}"></script>
</body>
</html>

PI/ong/templates/cadastro_um_ong.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <title>Cadastro - Dados Básicos</title>
    <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
    <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" />
    <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
</head>
<body id="page-top">
    
    <script src="{% static 'script/Password.js' %}"></script>

    {% if logout %}
        {% include 'Menu/menuCLoginBasic.html' %}
    {% else %}
        {% include 'Menu/menuSLoginBasic.html' %}
    {% endif %}  

    <section class="page-section" id="cadastro">
        <div class="container">
            <div class="text-center mb-4">
                <h2 class="section-heading text-uppercase">Cadastro de ONG's</h2>
                <h3 class="section-subheading">Informe os dados básicos da sua ONG</h3>
            </div>
            
            <form action="{% url 'ongpostcad' %}" method="post">
                {% csrf_token %}
                
                <div class="row justify-content-center">
                    <div class="col-md-4">
                        <div class="form-group">
                            <label for="id_nome">Nome da ONG:</label>
                            {{ form.nome }}
                        </div>
                    </div>
                </div>
                <br>
                <div class="row justify-content-center">
                    <div class="col-md-4">
                        <div class="form-group">
                            <label for="id_cnpj">CNPJ:</label>
                            {{ form.cnpj }}
                            {% if form.cnpj.errors %}
                                {% for error in form.cnpj.errors %}
                                    <label>{{ error }}</label>
                                {% endfor %}
                            {% endif %}
                        </div>
                    </div>
                </div>
                <br>
                <div class="row justify-content-center">
                    <div class="col-md-4">
                        <div class="form-group">
                            <label for="id_email_login">Email para login:</label>
                                {{ form.email_login }}      
                                {% if form.email_login.errors %}
                                    {% for error in form.email_login.errors %}
                                        <label>{{ error }}</label>
                                    {% endfor %}
                                {% endif %}    
                        </div>
                    </div>
                </div>
                <br>
                <div class="row justify-content-center">
                    <div class="col-md-4">
                        <div class="form-group">
                            <label for="id_senha_login">Senha para login:</label>
                            <div class="input-group">
                                {{ form.senha_login }}
                                <span class="input-group-text" id="img_olho" style="cursor: pointer;">
                                    <i class="fas fa-eye"></i>
                                </span>
                            </div>
                                {% if form.senha_login.errors %}
                                    {% for error in form.senha_login.errors %}
                                        <label>{{ error }}</label>
                                    {% endfor %}
                                {% endif %}
                            </div>
                        </div>
                    </div>
                    <br>
                <div class="row justify-content-center">
                    <div class="col-md-4">
                        <div class="form-group">
                            <label for="id_objetivo_ong">Objetivo da ONG:</label>
                            {{ form.objetivo_ong }}
                        </div>
                    </div>
                </div>

                <input type="hidden" name="etapa1" value="1">

                <div class="text-center mt-4">
                    <input type="submit" class="btn btn-primary btn-xl text-uppercase text-black" value="Próximo">
                </div>
            </form>
        </div>
    </section>

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js" crossorigin="anonymous"></script>
    <script src="{% static 'js/scripts.js' %}"></script>
</body>
</html>
z

PI/ong/templates/doacao_recebida.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <title>Doações - Produtos Alimentícios</title>
    <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
    <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" />
    <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
</head>
<body id="page-top">

    <script src="{% static 'script/Password.js' %}"></script>

    {% if logout %}
        {% include 'Menu/menuCLoginBasic.html' %}
    {% else %}
        {% include 'Menu/menuSLoginBasic.html' %}
    {% endif %}

    <section class="page-section" id="gerenciar-doacoes">
        <div class="container">
            <div class="text-center">
                <h2 class="section-heading text-uppercase">Doações de Produtos Alimentícios</h2>
                <h3 class="section-subheading">Lista de doações recebidas</h3>
            </div>
            <table class="table">
                <thead>
                    <tr>
                        <th>Nome da Empresa</th>
                        <th>Produto</th>
                        <th>Quantidade</th>
                        <th>Medida</th>
                        <th>Data</th>
                    </tr>
                </thead>
                <tbody>
                    {% for i in doacoes %}
                        <tr>
                            <td>{{ i.nome_empresa }}</td>
                            <td>{{ i.nome_produto }}</td>
                            <td>{{ i.quantidade_produto }}</td>
                            <td>{{ i.unidade_medida_produto }}</td>
                            <td>{{ i.data_doado_produto | date:"d/m/Y" }}</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
            <div>
                {% if doacoes.has_previous %}
                    <a href="{% url 'doacao_recebida' numero_pagina=doacoes.previous_page_number %}">Página anterior</a>
                {% endif %}
                {% if doacoes.has_next %}
                    <a href="{% url 'doacao_recebida' numero_pagina=doacoes.next_page_number %}">Próxima página</a>
                {% endif %}
            </div>
        </div>
    </section>
    <!-- Bootstrap core JS -->
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js" crossorigin="anonymous"></script>
    <script src="{% static 'js/scripts.js' %}"></script>
</body>
</html>