PI/PI/urls.py
from django.contrib import admin
from django.urls import path, include
from ong.urls import urlpatternscad as url_ong_cad, urlpatterns as url_ong
from empresa.urls import urlpatternscad as url_empresa_cad
from home.urls import urlpatterns as url_home
from pessoa.urls import urlpatternscad as url_pessoa_cad
from home.urls import urlpatterns as url_home
from login.urls import urlpatterns as url_login_logout
from pessoa.urls import urlpatternsdoacao as url_pessoa_doacao
from empresa.urls import urlpatternsdoacao as url_empresa_doacao

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cadastro/empresa/', include(url_empresa_cad)),
    path('cadastro/pessoa/', include(url_pessoa_cad)),
    path('cadastro/ong/', include(url_ong_cad)),
    path('home/', include(url_home)),
    path('auth/', include(url_login_logout)),
    path('doacao/pessoa/', include(url_pessoa_doacao)),
    path('doacao/', include(url_empresa_doacao)),
    path('', include(url_home)),
    path('distribuicao/', include(url_ong)),
    path('pessoa/pagamento/', include(url_pessoa_doacao))
]

PI/pessoa/urls.py
from django.urls import path
from pessoa.views.cadastro import PessoaCadastro
from pessoa.views.realiza_pagamento import PessoaDoacao, redireciona_cancelado, redireciona_sucesso, rendeniza_sucesso
from pessoa.views.pagamento_proprio import PessoaPagamentoProprio
from pessoa.views.pagamento_lista import PessoaPagamentoLista
from pessoa.views.pagamento_ranking import PessoaPagamentoRanking
urlpatternscad = [
    path('', PessoaCadastro.as_view(), name='pessoa'),
]

urlpatternsdoacao = [
    path('', PessoaDoacao.as_view(), name='pessoa_doacao'),
    path('sucessoredireciona', redireciona_sucesso, name='pessoa_doacao_sucesso'),
    path('sucesso', rendeniza_sucesso, name='pessoa_doacao_sucesso_rendeniza'),
    path('cancelado', redireciona_cancelado, name='pessoa_doacao_cancelado'),
    path('minha/<int:numero_pagina>', PessoaPagamentoProprio.as_view(), name='pessoa_pagamento_proprio'),
    path('lista/<int:numero_pagina>', PessoaPagamentoLista.as_view(), name='pessoa_pagamento_lista'),
    path('ranking/', PessoaPagamentoRanking.as_view(), name='pessoa_pagamento_ranking')
]

PI/pessoa/models.py
import uuid
from djongo import models
from django.contrib.auth.hashers import make_password, check_password

# Create your models here.

import uuid
from djongo import models

class Doacao(models.Model):
    id = models.ObjectIdField(primary_key=True)
    id_pessoa = models.CharField(max_length=256)
    valor_doacao = models.FloatField()
    data_doado = models.DateField(auto_now_add=True)


class Pessoa(models.Model):
    id = models.ObjectIdField(primary_key=True)
    nome_pessoa = models.CharField(max_length=100)
    cpf_pessoa = models.CharField(max_length=20)
    email_login_pessoa = models.EmailField(max_length=100)
    senha_login_pessoa = models.CharField(max_length=100)
    data_nascimento_pessoa = models.DateField()
    telefone_pessoa = models.CharField(max_length=20)
    valor_total_doado_pessoa = models.FloatField(default=0)

    def set_senha(self, senha_login_pessoa):
        self.senha_login_pessoa = make_password(senha_login_pessoa)

    def verifica_senha(self, senha_login_pessoa):
        return check_password(senha_login_pessoa, self.senha_login_pessoa)

PI/utils/models/model_padrao.py
from djongo import models
from django.contrib.auth.hashers import make_password, check_password

class ModeloPadrao(models.Model):
    id = models.ObjectIdField(primary_key=True)
    nome = models.CharField(max_length=100)
    cnpj = models.CharField(max_length=20)
    email_login = models.EmailField(max_length=100)
    senha_login = models.CharField(max_length=100)
    cep = models.CharField(max_length=20)
    estado = models.CharField(max_length=100)
    cidade = models.CharField(max_length=100)
    bairro = models.CharField(max_length=100)
    rua = models.CharField(max_length=100)
    numero = models.CharField(max_length=10)
    complemento = models.CharField(max_length=100, null=True, blank=True)
    nome_representante = models.CharField(max_length=100)
    cpf_representante = models.CharField(max_length=11)
    telefone_representante = models.CharField(max_length=20)
    email_representante = models.EmailField(max_length=100)

    def set_senha(self, senha_login):
        self.senha_login = make_password(senha_login)

    def verifica_senha(self, senha_login):
        return check_password(senha_login, self.senha_login)

    class Meta:
        abstract = True

PI/pessoa/forms.py
from django import forms
from pessoa.models import Pessoa
from empresa.models import Empresa
from datetime import date
from django.utils import timezone
import re 
from services.validacao import Validacao

class PessoaForm(forms.ModelForm):
    class Meta:
        model = Pessoa
        fields = [
            'nome_pessoa',
            'cpf_pessoa',
            'email_login_pessoa',
            'senha_login_pessoa',
            'data_nascimento_pessoa',
            'telefone_pessoa'
        ]
        widgets = {
            'nome_pessoa': forms.TextInput(attrs={
                'class': 'form-control',
            }),
            'cpf_pessoa': forms.TextInput(attrs={
                'class': 'form-control',
                'maxlength': '14',
                'oninput': "this.value=this.value.replace(/[^0-9]/g,'');",
            }),
            'email_login_pessoa': forms.EmailInput(attrs={
                'class': 'form-control',
            }),
            'senha_login_pessoa': forms.PasswordInput(attrs={
                'type': 'password',
                'minlength': '8',
                'class': 'form-control',
            }),
            'data_nascimento_pessoa': forms.DateInput(attrs={
                'type': 'date',
                'min': '1900-01-01',
                'max': date.today(),
                'onkeydown': 'return false',
                'class': 'form-control',
            }),
            'telefone_pessoa': forms.TextInput(attrs={
                'class': 'form-control',
                'maxlength': '15',
                'oninput': "this.value=this.value.replace(/[^0-9]/g,'');",
            }),
        }
    
    def clean_nome_pessoa(self):
        nome_pessoa = self.cleaned_data.get('nome_pessoa')
        nome_pessoa = Validacao.verifica_nome_representante(nome_pessoa)
        if not nome_pessoa:
            raise forms.ValidationError('Nome inválido')
        return nome_pessoa
    
    def clean_cpf_pessoa(self):
        cpf_pessoa = self.cleaned_data.get('cpf_pessoa')
        if Pessoa.objects.filter(cpf_pessoa=cpf_pessoa):
            raise forms.ValidationError('CPF já cadastrado')
        cpf_pessoa = Validacao.verifica_cpf(cpf_pessoa)
        if not cpf_pessoa:
            raise forms.ValidationError('CPF inválido')
        return cpf_pessoa

    def clean_email_login_pessoa(self):
        email_login_pessoa = self.cleaned_data.get('email_login_pessoa')
        if Pessoa.objects.filter(email_login_pessoa=email_login_pessoa) or Empresa.objects.filter(email_login=email_login_pessoa):
            raise forms.ValidationError('Email já cadastrado')
        return email_login_pessoa
        
    def clean_senha_login_pessoa(self):
        senha_login_pessoa = self.cleaned_data.get('senha_login_pessoa')
        senha_login_pessoa = Validacao.verifica_senha(senha_login_pessoa)
        if not senha_login_pessoa:
            raise forms.ValidationError('Senha inválida')
        return senha_login_pessoa

    def clean_telefone_pessoa(self):
        telefone_pessoa = self.cleaned_data.get('telefone_pessoa')
        telefone_pessoa = Validacao.verifica_telefone(telefone_pessoa)
        if not telefone_pessoa:
            raise forms.ValidationError('Número de telefone inválido')
        return telefone_pessoa
    
    def clean_data_nascimento_pessoa(self):
        data_nascimento_pessoa = self.cleaned_data.get('data_nascimento_pessoa')
        data_nascimento_pessoa = Validacao.verifica_data_nascimento(data_nascimento_pessoa)
        if not data_nascimento_pessoa:
            raise forms.ValidationError('É necessário ser maior de idade')
        return data_nascimento_pessoa

PI/empresa/views/cadastro.py
from django.shortcuts import render, redirect
from empresa.forms import EmpresaFormUm, EmpresaFormDois, EmpresaFormTres, EmpresaCompleta
from django.views import View

class EmpresaCadastro(View):
    def __init__(self, *args, **kwargs):
        self.templates = {
            1: ['cadastro_um.html', EmpresaFormUm],
            2: ['cadastro_dois.html', EmpresaFormDois],
            3: ['cadastro_tres.html', EmpresaFormTres]
        }
        super().__init__(*args, **kwargs)
    def get(self, request, etapa):
        template = self.templates[etapa][0]
        form = self.templates[etapa][1]()
        login = {
            'id_empresa': 'empresa',
            'id_ong': 'ong',
            'id_pessoa': 'pessoa'
        }
        for k, v in login.items():
            if request.session.get(k):
                context = v
                break
            context = ''
        if etapa > 1 and not f'etapa{etapa-1}' in request.session:
            return redirect('empresagetcad', etapa=1)
        return render(request=request, template_name=template, context={'form': form, 'logout': context }) 
    def post(self, request):
        chave = 1 if request.POST.get('etapa1', '') else (2 if request.POST.get('etapa2', '') else (3 if request.POST.get('etapa3', '') else ''))
        if chave == '':
            return redirect('home')
        form = self.templates[chave][1](request.POST)
        if form.is_valid():
            if chave == 1:
                request.session['empresa'] = form.cleaned_data
                request.session['etapa1'] = True
            elif chave == 2:
                request.session['empresa'] = request.session['empresa'] | form.cleaned_data
                request.session['etapa2'] = True
            elif chave == 3:
                form_completo = EmpresaCompleta(request.session['empresa'] | form.cleaned_data)
                empresa = form_completo.save(commit=False)
                empresa.set_senha(form_completo.cleaned_data['senha_login'])
                empresa.save()
                return redirect('login')
            request.session.modified = True
            return redirect('empresagetcad', etapa = chave + 1)
        else:
            return render(request=request, template_name=self.templates[chave][0], context={'form': form}, status=400)

PI/pessoa/views/cadastro.py
from django.shortcuts import render, redirect
from pessoa.forms import PessoaForm
from django.views import View

# Create your views here.

class PessoaCadastro(View):
    def get(self, request):
        form = PessoaForm()
        return render(request=request, template_name='cadastro.html',  context={'form': form})
    def post(self, request):
        form = PessoaForm(request.POST)
        if form.is_valid():
            pessoa = form.save(commit=False)
            pessoa.set_senha(form.cleaned_data['senha_login_pessoa'])
            pessoa.save()
            return redirect('login')
        else:
            return render(request=request, template_name='cadastro.html', context={'form': form}, status=400)

PI/pessoa/views/pagamento_lista.py
from django.shortcuts import render
from pessoa.models import Pessoa, Doacao
from django.views import View
from django.core.paginator import Paginator

class PessoaPagamentoLista(View):
    def get(self, request, numero_pagina):
        login = {
            'id_empresa': 'empresa',
            'id_ong': 'ong',
            'id_pessoa': 'pessoa'
        }
        for k, v in login.items():
            if request.session.get(k):
                context = v
                break
            context = ''
        pessoas = {i.id: i.nome_pessoa for i in Pessoa.objects.all()}
        doacoes = Doacao.objects.all()
        lista_contexto = [
            {
                'nome_pessoa': pessoas.get(int(i.id_pessoa)),
                'valor_doado': int(i.valor_doacao) if i.valor_doacao % 10 == 0 else i.valor_doacao,
                'data_doado': i.data_doado   
            } for i in doacoes
        ]
        doacao_paginada = Paginator(lista_contexto, 10)
        pagina = doacao_paginada.get_page(numero_pagina)
        return render(request=request, template_name='visualiza_pagamento.html', context={'doacoes': pagina, 'logout': context})

PI/pessoa/views/pagamento_proprio.py
from django.shortcuts import render, redirect
from pessoa.models import Pessoa, Doacao
from django.views import View
from django.core.paginator import Paginator

class PessoaPagamentoProprio(View):
    def dispatch(self, request, *args, **kwargs):
        if 'id_pessoa' not in request.session:
            return redirect('login')
        return super().dispatch(request, *args, **kwargs)
    def get(self, request, numero_pagina):
        doacoes = Doacao.objects.filter(id_pessoa=request.session['id_pessoa'])
        pessoa = Pessoa.objects.get(id=request.session['id_pessoa']).nome_pessoa
        lista_contexto = [
            {
                'valor_doado': int(i.valor_doacao) if i.valor_doacao % 10 == 0 else i.valor_doacao,
                'data_doado': i.data_doado
            } for i in doacoes
        ]
        doacao_paginada = Paginator(lista_contexto, 10)
        pagina = doacao_paginada.get_page(numero_pagina)
        return render(request=request, template_name='visualiza_pagamento_meu.html', context={'doacoes': pagina, 'nome': pessoa})

PI/pessoa/views/pagamento_ranking.py
from django.shortcuts import render
from pessoa.models import Pessoa
from django.views import View
    
class PessoaPagamentoRanking(View):
    def get(self, request):
        login = {
            'id_empresa': 'empresa',
            'id_ong': 'ong',
            'id_pessoa': 'pessoa'
        }
        for k, v in login.items():
            if request.session.get(k):
                context = v 
                break
            context = ''
        pessoas = Pessoa.objects.all().order_by('-valor_total_doado_pessoa')[:10]
        lista_contexto = [
            {
                'nome_pessoa': i.nome_pessoa,
                'valor_total_doado_pessoa': int(i.valor_total_doado_pessoa) if i.valor_total_doado_pessoa % 10 == 0 else i.valor_total_doado_pessoa
            } for i in pessoas
        ]
        return render(request=request, template_name='ranking_pagamento.html', context={'pessoas': lista_contexto, 'logout': context})

PI/pessoa/views/realiza_pagamento.py
from django.shortcuts import render, redirect
from pessoa.models import Pessoa, Doacao
from django.views import View
from django.conf import settings
from django.urls import reverse
from django.http import JsonResponse
import stripe

stripe.api_key = settings.STRIPE_SECRET_KEY

class PessoaDoacao(View):
    def dispatch(self, request, *args, **kwargs):
        if 'id_pessoa' not in request.session:
            return redirect('login')
        return super().dispatch(request, *args, **kwargs)
    def get(self, request):
        return render(request=request, template_name='pix.html', context={'logout': 'pessoa'})
    def post(self, request):
        site =  'http://127.0.0.1:8000/'
        valor = int(request.POST['valor'])
        sessao_pagamento = stripe.checkout.Session.create(
            payment_method_types=['card'],
            line_items=[
                {
                    'price_data': {
                        'currency': 'brl',
                        'product_data': {
                            'name': f'Doacão de {valor} reais'
                        },
                        'unit_amount': valor * 100
                    },
                    'quantity': 1
                }
            ],
            mode = 'payment',
            success_url= site + '/pessoa/pagamento/sucessoredireciona?session_id={CHECKOUT_SESSION_ID}',
            cancel_url= site + '/pessoa/pagamento/cancelado',
        )
        return JsonResponse({'id': sessao_pagamento.id})
    
def rendeniza_sucesso(request):
    return render(request=request, template_name='success.html', context={'logout': 'pessoa'})

def redireciona_sucesso(request):
    session_id = request.GET.get('session_id')
    if session_id:
        sessao = stripe.checkout.Session.retrieve(session_id)
        valor = sessao.amount_total / 100
        Doacao.objects.create(id_pessoa = request.session['id_pessoa'], valor_doacao = valor)
        pessoa = Pessoa.objects.get(id=request.session['id_pessoa'])
        pessoa.valor_total_doado_pessoa += valor
        pessoa.save()
    return redirect(reverse('pessoa_doacao_sucesso_rendeniza'))

def redireciona_cancelado(request):
    return render(request=request, template_name='cancel.html')

PI/pessoa/templates/cadastro.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Cadastro de Pessoa</title>
    <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
    <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" />
    <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
</head>
<body>

    <script src="{% static 'script/Password.js' %}"></script>

    {% if logout %}
        {% include 'Menu/menuCLoginBasic.html' %}
    {% else %}
        {% include 'Menu/menuSLoginBasic.html' %}
    {% endif %}

    <section class="page-section d-flex justify-content-center align-items-center" id="cadastro">
        <div class="container">
            <div class="text-center mb-4">
                <h2 class="section-heading text-uppercase">Cadastro de Pessoa</h2>
                <h3 class="section-subheading">Informe os dados da pessoa</h3>
            </div>
            <form id="form_pessoa" action="{% url 'pessoa' %}" method="post">
                {% csrf_token %}
                
                <div class="row justify-content-center mb-3">
                    <div class="col-md-4">
                        <div class="form-group">
                            <label for="id_nome_pessoa">Nome completo:</label>
                            {{ form.nome_pessoa }}
                            {% if form.nome_pessoa.errors %}
                                <div class="text-danger">
                                    {% for error in form.nome_pessoa.errors %}
                                        <p>{{ error }}</p>
                                    {% endfor %}
                                </div>
                            {% endif %}
                        </div>
                    </div>
                </div>

                <div class="row justify-content-center mb-3">
                    <div class="col-md-4">
                        <div class="form-group">
                            <label for="id_cpf_pessoa">CPF:</label>
                            {{ form.cpf_pessoa }}
                            {% if form.cpf_pessoa.errors %}
                                <div class="text-danger">
                                    {% for error in form.cpf_pessoa.errors %}
                                        <p>{{ error }}</p>
                                    {% endfor %}
                                </div>
                            {% endif %}
                        </div>
                    </div>
                </div>

                <div class="row justify-content-center mb-3">
                    <div class="col-md-4">
                        <div class="form-group">
                            <label for="id_email_login_pessoa">E-mail:</label>
                            {{ form.email_login_pessoa }}
                            {% if form.email_login_pessoa.errors %}
                                <div class="text-danger">
                                    {% for error in form.email_login_pessoa.errors %}
                                        <p>{{ error }}</p>
                                    {% endfor %}
                                </div>
                            {% endif %}
                        </div>
                    </div>
                </div>

                <div class="row justify-content-center mb-3">
                    <div class="col-md-4">
                        <div class="form-group">
                            <label for="id_senha_login">Senha:</label>
                            <div class="input-group">
                                {{ form.senha_login_pessoa }}
                                <span class="input-group-text" id="img_olho" style="cursor: pointer;">
                                    <i class="fas fa-eye"></i>
                                </span>
                            </div>
                            {% if form.senha_login_pessoa.errors %}
                                <div class="text-danger">
                                    {% for error in form.senha_login_pessoa.errors %}
                                        <p>{{ error }}</p>
                                    {% endfor %}
                                </div>
                            {% endif %}
                        </div>
                    </div>
                </div>

                <div class="row justify-content-center mb-3">
                    <div class="col-md-4">
                        <div class="form-group">
                            <label for="id_data_nascimento_pessoa">Data de nascimento:</label>
                            {{ form.data_nascimento_pessoa }}
                            {% if form.data_nascimento_pessoa.errors %}
                                <div class="text-danger">
                                    {% for error in form.data_nascimento_pessoa.errors %}
                                        <p>{{ error }}</p>
                                    {% endfor %}
                                </div>
                            {% endif %}
                        </div>
                    </div>
                </div>

                <div class="row justify-content-center mb-3">
                    <div class="col-md-4">
                        <div class="form-group">
                            <label for="id_telefone_pessoa">Telefone:</label>
                            {{ form.telefone_pessoa }}
                            {% if form.telefone_pessoa.errors %}
                                <div class="text-danger">
                                    {% for error in form.telefone_pessoa.errors %}
                                        <p>{{ error }}</p>
                                    {% endfor %}
                                </div>
                            {% endif %}
                        </div>
                    </div>
                </div>

                <div class="text-center mt-4">
                    <input type="submit" class="btn btn-primary btn-xl text-uppercase text-black" value="Enviar">
                </div>
            </form>
        </div>
    </section>

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js" crossorigin="anonymous"></script>
    <script src="{% static 'js/scripts.js' %}"></script>
</body>
</html>

PI/pessoa/templates/cancel.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Pagamento Cancelado</title>
    <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
    <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" />
    <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
</head>
<body>

    <script src="{% static 'script/Password.js' %}"></script>
    
    {% if logout %}
        {% include 'Menu/menuCLoginBasic.html' %}
    {% else %}
        {% include 'Menu/menuSLoginBasic.html' %}
    {% endif %}

    <section class="page-section d-flex justify-content-center align-items-center" id="pagamento-cancelado">
        <div class="container">
            <div class="text-center mb-4">
                <h2 class="section-heading text-uppercase">Pagamento Cancelado</h2>
                <h3 class="section-subheading">Seu pagamento foi cancelado. Se você tiver alguma dúvida, entre em contato conosco.</h3>
            </div>

            <div class="text-center mt-4">
                <a href="{% url 'home' %}" class="btn btn-primary btn-xl text-uppercase">Voltar para a página inicial</a>
            </div>
        </div>
    </section>

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js" crossorigin="anonymous"></script>
    <script src="{% static 'js/scripts.js' %}"></script>
</body>
</html>

PI/pessoa/templates/pix.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Checkout</title>
    <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
    <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" />
    <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
</head>
<body>

    <script src="{% static 'script/Password.js' %}"></script>

    {% include 'Menu/menuCLoginBasic.html' %}

    <section class="page-section d-flex justify-content-center align-items-center" id="checkout">
        <div class="container">
            <div class="text-center mb-4">
                <h2 class="section-heading text-uppercase">Ajude a combater a fome</h2>
                <h3 class="section-subheading">Sua contribuição faz a diferença!</h3>
            </div>

            <div class="row g-4 justify-content-center">
                        <form action="{% url 'pessoa_doacao' %}" id="form_1" onsubmit="return envia_formulario(event)">
                            <h5 class="text-center">Escolha um valor para contribuir</h4>
                            {% csrf_token %}
                            <input type="hidden" value="10" name="valor">
                            <div class="text-center">
                                <input type="submit" value="10 reais" class="btn btn-primary btn-xl text-uppercase text-black">
                            </div>
                        </form>
                        <form action="{% url 'pessoa_doacao' %}" id="form_2" onsubmit="return envia_formulario(event)">
                            {% csrf_token %}
                            <input type="hidden" value="30" name="valor">
                            <div class="text-center">
                                <input type="submit" value="30 reais" class="btn btn-primary btn-xl text-uppercase text-black">
                            </div>
                        </form>
                        <form action="{% url 'pessoa_doacao' %}" id="form_3" onsubmit="return envia_formulario(event)">
                            {% csrf_token %}
                            <input type="hidden" value="50" name="valor">
                            <div class="text-center">
                                <input type="submit" value="50 reais" class="btn btn-primary btn-xl text-uppercase text-black">
                            </div>
                        </form> 
            </div>
        </div>
    </section>

    <script src="https://js.stripe.com/v3"></script>
    <script>
        const stripe = Stripe('pk_test_51QKUd8GK5KkbiX4wOiFT7IAIyrP8MjfQrD3T2uAhuRk5Gu75wFeZpRwWyx3GbTaohGGGl2A4ikWhLt9A0r6VhbkS00E9HtgcUy')

        function envia_formulario(event) {
            event.preventDefault()
            const form = document.getElementById(event.target.getAttribute('id'))
            const form_data = new FormData(form)
            const url = form.action;

            fetch(url, {
                method: 'POST',
                body: form_data
            })
            .then(function(response) {
                return response.json();
            })
            .then(function(id){
                return stripe.redirectToCheckout({sessionId: id.id})
            })
            .then(function(result){
                if (result.error) {
                    console.log(result.error.message)
                }
            })
        }
    </script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js" crossorigin="anonymous"></script>
    <script src="{% static 'js/scripts.js' %}"></script>
</body>
</html>

PI/pessoa/templates/ranking_pagamento.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <title>Minhas doações</title>
    <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
    <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" />
    <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
</head>
<body id="page-top">

    <script src="{% static 'script/Password.js' %}"></script>

    {% if logout %}
        {% include 'Menu/menuCLoginBasic.html' %}
    {% else %}
        {% include 'Menu/menuSLoginBasic.html' %}
    {% endif %}

    <section class="page-section" id="gerenciar-doacoes">
        <div class="container">
            <div class="text-center">
                <h2 class="section-heading text-uppercase">Maiores doares</h2>
                <h3 class="section-subheading">Ranking</h3>
            </div>
                <table class="table table-bordered">
                    <thead>
                        <tr>
                            <th>Posição no ranking</th>
                            <th>Nome da pessoa</th>
                            <th>Valor total doado (reais)</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for i in pessoas %}
                            <tr>
                                <td>{{ forloop.counter }}</td>
                                <td>{{ i.nome_pessoa }}</td>
                                <td>{{ i.valor_total_doado_pessoa }}</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
    </section>

    <!-- Bootstrap core JS -->
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js" crossorigin="anonymous"></script>
    <script src="{% static 'js/scripts.js' %}"></script>
    <script>
        function modalDoacaoAlimento() {
            const donationModal = new bootstrap.Modal(document.getElementById('donationModal'));
            donationModal.show();
        }
    </script>
</body>
</html>